Repository debezium/debezium, pull requests merged in 2021-11, with the labels that each got.

#2880 DBZ-4077 Fix NPE with Oracle test suite
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 1.8

#2881 DBZ-4233 CHAR / NCHAR precision not derived from DDL
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
Labels: 1.6, 1.7, 1.8

#2892 DBZ-4241 Add more assertions for MySqlTimestampColumnIT
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlTimestampColumnIT.java
Labels: 1.8

#2896 DBZ-4159 Make Oracle Infinispan trx cache layout forward compatible
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/TransactionAdapter.java
Labels: 1.8

#2895 DBZ-4204 Allow ORA-04030 exceptions to be retried
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 1.6, 1.7, 1.8

#2899 DBZ-4204 Allow ORA-04030 exceptions to be retried
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 1.7

#2904 DBZ-4252 Remove unused code
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/DmlParser.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
  debezium-microbenchmark-oracle/src/main/java/io/debezium/performance/connector/oracle/parser/LogMinerDmlParserPerf.java
Labels: 1.8

#2911 DBZ-4255 Reduce verbosity of logging Oracle memory metrics
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 1.7, 1.8

#2912 DBZ-3708 Add `debezium.sink.redis.null.value` configurable option
  debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisStreamChangeConsumer.java
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
Labels: 1.8

#2853 DBZ-4196 Support schema changes during incremental snapshot
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotIT.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
  debezium-core/src/main/java/io/debezium/config/CommonConnectorConfig.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java
  debezium-core/src/main/java/io/debezium/relational/ColumnImpl.java
  debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
  debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotWithSchemaChangesSupportTest.java
Labels: 1.8

#2945 DBZ-4224 Fix parsing creation of queue tables
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.6, 1.7, 1.8

#2952 DBZ-4322 Test Oracle 12.2.0.1 on CI
  jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
Labels: 1.8

#2990 DBZ-4127 Document `incremental.snapshot.chunk.size`
  documentation/modules/ROOT/pages/connectors/db2.adoc
  documentation/modules/ROOT/pages/connectors/mysql.adoc
  documentation/modules/ROOT/pages/connectors/oracle.adoc
  documentation/modules/ROOT/pages/connectors/postgresql.adoc
  documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Labels: 1.6, 1.7, 1.8
