Repository debezium/debezium, pull requests merged in 2021-10, with the labels that each got.

#2731 DBZ-4034 Add missing tokens for DDL parser
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql
Labels: 1.8

#2752 [1.6] DBZ-4067 Correctly calculate mining session boundaries
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryResultProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 1.6

#2737 DBZ-3907 Publish debezium tool images to dockerhub using Jenkins
  jenkins-jobs/job-dsl/deploy_debezium_tool_images.groovy
  jenkins-jobs/pipelines/build-debezium-tool-images.groovy
Labels: 1.8

#2761 DBZ-4106 Don't continuously reconfigure DatabaseHistory
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/InfinispanLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
  debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
Labels: 1.7, 1.8

#2762 DBZ-4106 Don't continuously reconfigure DatabaseHistory
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
  debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseSchema.java
Labels: 1.6

#2870 DBZ-4215 Support MySQL dual password syntax
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/ddl_alter.sql
Labels: 1.7, 1.8
