Repository debezium/debezium, pull requests merged in 2022-11, with the labels that each got.

#4016 DBZ-5786 Upgrade to Quarkus 2.14.0.Final
  pom.xml
Labels: 2.0, 2.1

#4036 DBZ-5773 Correctly discard LOB_ERASE events
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
Labels: 1.9, 2.0, 2.1

#3938 DBZ-5648 Move LogMiner RegEx handling into Java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
Labels: 2.1

#4043 DBZ-5816 Introduce FAQ section; document ORA-01555
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.0, 2.1

#4052 DBZ-5824 refactor GitHub Actions deprecated set-output command
  .github/workflows/contributor-check.yml
  .github/workflows/octocat-commits-check.yml
  .github/workflows/oracle-workflow-test.yml
  .github/workflows/sanity-check.yml
Labels: 2.0, 2.1

#4053 DBZ-5789 Remove obsolete info about PG metadata from doc
  documentation/modules/ROOT/pages/connectors/postgresql.adoc
Labels: 2.0, 2.1

#4057 AbstractLogMinerEventProcessor DEBUG to TRACE loglevel
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 2.1

#4040 DBZ-5808 update docs to reflect Cassandra varint.handling.mode config property
  documentation/modules/ROOT/pages/connectors/cassandra.adoc
Labels: waits for other PR, 2.1

#4055 DBZ-5807 update docs to reflect Cassandra decimal.handling.mode config property
  COPYRIGHT.txt
  documentation/modules/ROOT/pages/connectors/cassandra.adoc
Labels: waits for other PR, 2.1

#4070 DBZ-5843 Invalid Java object for schema with type FLOAT64: class java.lang.Float
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlValueConverters.java
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlFloatIT.java
  debezium-connector-mysql/src/test/resources/ddl/float_test.sql
Labels: 2.0, 2.1

#4067 DBZ-5850 Fix test OracleConnectorIT shouldIgnoreAllTablesInExcludedSchemas
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 2.1
