Repository debezium/debezium, pull requests merged in 2022-01, with the labels that each got.

#3117 DBZ-4546 Improve Virtual Column DDL syntax support
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 1.7, 1.8, 1.9

#3118 DBZ-4536 Make OracleErrorHandler more flexible of retriable errors
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 1.7, 1.8, 1.9

#3139 DBZ-4571 Support older Oracle degree of parallelism DDL syntax
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.8, 1.9

#3157 DBZ-4581 Remove Oracle benchmark dependency on XStreams
  debezium-microbenchmark-oracle/pom.xml
Labels: 1.9

#3154 DBZ-4567 DDL and DML events exclude built-in schemas
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
Labels: 1.8, 1.9

#3156 DBZ-4580 Remove non-plugin `maven-filtering` from build plugins
  debezium-parent/pom.xml
  pom.xml
Labels: 1.9

#3160 DBZ-4595 Support Oracle ROWID data type
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleRowIdDataTypeIT.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9

#3163 DBZ-4613 Fix property name for `debezium.transforms.<name>.type`
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
Labels: 1.8, 1.9

#3159 DBZ-4597 Add Oracle FAQ entry about "Logs don't contain offset"
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.8, 1.9

#3170 [docs] Fix missing conditional
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 1.7, 1.8, 1.9

#3172 DBZ-4609 Using partition_extended_names for drop partition
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 1.8, 1.9

#3174 DBZ-4640 Parse including keyword column table ddl error
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlAntlrDdlParserTest.java
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
Labels: 1.8, 1.9
