Repository debezium/debezium, pull requests merged in 2022-08, with the labels that each got.

#3759 DBZ-5434 Translation from mongodb document to kafka connect schema fails when nested arrays contain no elements
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/transforms/MongoDataConverter.java
  debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/transforms/ExtractNewDocumentStateTestIT.java
Labels: 1.9, 2.0

#3771 DBZ-5472 Support CREATE INDEX using TABLESPACE with quoted identifiers
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.9, 2.0

#3772 DBZ-5476 Fix record accumulator during statistics log entry
  debezium-core/src/main/java/io/debezium/connector/common/BaseSourceTask.java
Labels: 1.9, 2.0

#3766 DBZ-5453 Add `stop-snapshot` MySQL read-only Kafka signal
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/StopSnapshotKafkaSignal.java
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
  documentation/modules/ROOT/pages/connectors/mysql.adoc
Labels: 2.0

#3776 DBZ-5478: Restart SQL Server task on "Socket closed" exception
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
Labels: 1.9, 2.0

#3765 DBZ-4329 Don't send fileds with obsolete values
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresEventMetadataProvider.java
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresSourceInfoStructMaker.java
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/SourceInfo.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
Labels: 1.9, 2.0

#3777 DBZ-5479 Retry MongoNodeIsRecoveringException when failover
  COPYRIGHT.txt
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbErrorHandler.java
  jenkins-jobs/scripts/config/Aliases.txt
Labels: 1.9, 2.0

#3780 DBZ-5487 Adapt create function syntax of mariadb
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
Labels: 2.0

#3784 DBZ-5483 Fix testStopSnapshotKafkaSignal random failure
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/ReadOnlyIncrementalSnapshotIT.java
Labels: 2.0

#3785 DBZ-5493 Upgrade PostgreSQL driver to 42.4.1
  pom.xml
Labels: dependencies, 2.0

#3761 DBZ-5463 Upgrade Kafka to 3.2.1
  documentation/antora.yml
  pom.xml
Labels: 2.0

#3800 DBZ-5506 duplicate call to config.validateAndRecord() in RedisDatabaseHistory
  debezium-server/debezium-server-redis/src/main/java/io/debezium/server/redis/RedisDatabaseHistory.java
Labels: 1.9, 2.0

#3699 DBZ-5327 Smart Backfills
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotChangeEventSource.java
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbIncrementalSnapshotContext.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlReadOnlyIncrementalSnapshotChangeEventSource.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/ExecuteSnapshotKafkaSignal.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnection.java
  debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
  debezium-core/src/main/java/io/debezium/pipeline/signal/AbstractSnapshotSignal.java
  debezium-core/src/main/java/io/debezium/pipeline/signal/ExecuteSnapshot.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/DataCollection.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotChangeEventSource.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/IncrementalSnapshotContext.java
  debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
  debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
  documentation/modules/ROOT/pages/connectors/mysql.adoc
  documentation/modules/ROOT/partials/modules/all-connectors/con-connector-ad-hoc-snapshots.adoc
  documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
Labels: 2.0, pending docs

#3807 DBZ-5526 Support JSON-based CHECK conditions
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.9, 2.0

#3805 DBZ-5521 Fix concatenation operator handling in LogMiner DML parser
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
Labels: 1.9, 2.0

#3809 DBZ-5533 Unit test fails on Windows
  debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
Labels: 1.9, 2.0

#3810 DBZ-5327 Fix Oracle/Db2 test failures
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
  debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
Labels: 2.0

#3837 [docs] Fix placeholder substitutions
  documentation/modules/ROOT/pages/operations/kubernetes.adoc
  documentation/modules/ROOT/pages/operations/openshift.adoc
Labels: 1.9, 2.0

#3840 DBZ-5569 Oracle connector's max.queue.size.in.bytes is invalid
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
  debezium-core/src/main/java/io/debezium/connector/base/ChangeEventQueue.java
Labels: 1.9, 2.0
