Repository debezium/debezium, pull requests merged in 2022-04, with the labels that each got.

#3368 DBZ-4937 Correctly read/write snapshot_scn and snapshot_pending_trx offsets
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java
Labels: 1.9

#3381 DBZ-4936 Don't re-emit transaction on restart with commit SCN equal to offset commit SCN
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 1.9, 2.0

#3380 DBZ-4879 Correctly resolve archive-log-only SCN mining range
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 1.9, 2.0

#3390 DBZ-3318 Add integration test for `database.url`
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 2.0

#3389 DBZ-4932 Use LCR v1 format with Oracle 12.0 and 12.1
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
Labels: 1.9, 2.0

#3388 DBZ-4953 Correctly handle TRUNCATE when LOB is enabled
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 1.9, 2.0

#3396 DBZ-4949 Use Java 17 for Cassandra connector tests
  .github/workflows/debezium-workflow.yml
Labels: 2.0

#3402 DBZ-4978 Avoid NPE during Oracle connector shutdown
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorTask.java
Labels: 1.9, 2.0

#3403 DBZ-4987 Propagate up all exceptions from LCR handler
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
Labels: 1.9, 2.0

#3405 DBZ-4994 Fix LOB locator event parsing with escaped single quotes
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/SelectLobParser.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SelectLobParserTest.java
Labels: 1.9, 2.0

#3421 DBZ-5028 Scope OracleOffsetContextTest to the LogMiner adapter
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java
Labels: 1.9, 2.0

#3434 DBZ-5058 Fix formatting
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
Labels: 1.9, 2.0

#3411 DBZ-5005 adjust LogMiner batch size based on comparison with currently used batch size
  COPYRIGHT.txt
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 1.9, 2.0

#3433 DBZ-5057 Document ORA-01882 and Oracle 11g
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.0

#3435 DBZ-4762 Document excluded built-in schemas
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0

#3432 DBZ-5054 Wait for the MySQL to be fully started before starting tests
  debezium-connector-mysql/pom.xml
Labels: 1.9, 2.0
