Repository debezium/debezium, pull requests merged in 2022-10, with the labels that each got.

#3931 [docs] Remove oplog capture mode from MongoDB documentation
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 2.0

#3930 [docs] Mention that Mongo change stream mode is not supported on 3.x
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 1.9

#3976 DBZ-5726 Use DEFAULT_COLLATION_CLAUSE
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.9, 2.0, 2.1

#3972 DBZ-5682 Allow unique index NULL values in trx reconciliation
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 1.9, 2.0, 2.1

#3974 DBZ-5352 Clarify table eligibility rules for schema history topic
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0, 2.1

#3993 DBZ-5615 Mask additional credentials during log events
  debezium-core/src/main/java/io/debezium/config/Configuration.java
Labels: 1.9, 2.0, 2.1

#3998 DBZ-5760 Only log full row data at TRACE level
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/signal/KafkaSignalThread.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/memory/MemoryLogMinerEventProcessor.java
  debezium-core/src/main/java/io/debezium/util/Loggings.java
  debezium-core/src/main/java/io/debezium/util/Throwables.java
  debezium-storage/debezium-storage-file/src/main/java/io/debezium/storage/file/history/FileSchemaHistory.java
  debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaSchemaHistory.java
  debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java
Labels: 2.0, 2.1
