Repository debezium/debezium, pull requests merged in 2022-06, with the labels that each got.

#3552 DBZ-5179 Use BoundedLinkedHashSet to avoid high memory usage
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleStreamingMetricsTest.java
  debezium-core/src/main/java/io/debezium/util/LRUCacheMap.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0

#3456 DBZ-5085 Enforce read-consistency determining snapshot offsets
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/StreamingAdapter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFile.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XStreamAdapter.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 1.9, 2.0

#3565 DBZ-5184 Introduce Kafka 2.x Jenkins Job
  jenkins-jobs/job-dsl/kafka_1_x_test.groovy
Labels: 2.0

#3562 DBZ-4806 Upgrade to Quarkus 2.9.2.Final
  pom.xml
Labels: 2.0

#3561 DBZ-5153 Update MBean name references for SQL Server
  documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-snapshot-metrics.adoc
  documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-monitoring-streaming-metrics.adoc
Labels: 1.9, 2.0

#3574 DBZ-5202 Add retry/delay to offset transaction id resolution
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
Labels: 1.9, 2.0

#3580 DBZ-5204 Do not cache connection details in `TypeRegistry`.
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/TypeRegistry.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
Labels: 1.9, 2.0

#3585 DBZ-5210 Support constraint_clauses in add_modify_drop_column_clauses
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 1.9, 2.0

#3586 DBZ-5224 Remove invalid scope
  debezium-server/debezium-server-dist/pom.xml
Labels: 2.0

#3587 DBZ-5045 Use correct buffer type value after deprecated `infinispan` …
  debezium-connector-oracle/pom.xml
Labels: 2.0

#3597 DBZ-5226 Improve test wait-time performance
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 2.0

#3596 DBZ-5230 Extend syntax support for ALTER TABLE TRUNCATE PARTITION
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 1.9, 2.0

#3604 DBZ-5237 Allow LOB storage cause to use quoted string identifiers
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.9, 2.0

#3612 DBZ-5258 Fix test assertions using static database names
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SignalsIT.java
Labels: 1.9, 2.0

#3613 DBZ-5257 Source info table order deterministic for rename schema changes
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
Labels: 1.9, 2.0

#3616 DBZ-5259 Upgrade to Quarkus 2.10.0.Final
  pom.xml
Labels: 2.0

#3600 DBZ-4834 Fix incremental snapshot of table added to include list
  debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/IncrementalSnapshotIT.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotCaseSensitiveIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/IncrementalSnapshotIT.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/IncrementalSnapshotIT.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotIT.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/IncrementalSnapshotWithRecompileIT.java
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotChangeEventSource.java
  debezium-embedded/src/test/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotTest.java
Labels: 1.9, 2.0

#3615 DBZ-5256 Add `internal.log.mining.transaction.snapshot.boundary.mode`option
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerAdapter.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 1.9, 2.0

#2660 DBZ-3942 Load correct last commit LSN from offsets
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresOffsetContext.java
Labels: 1.9

#3636 DBZ-5287 Upgrade MongoDB driver to 4.6.1
  pom.xml
Labels: 2.0

#3635 DBZ-5261 Upgrade PostgreSQL driver to 42.4.0
  pom.xml
Labels: 2.0

#3638 DBZ-5289 Upgrade Oracle driver to 21.6.0.0
  pom.xml
Labels: 2.0

#3637 DBZ-5288 Upgrade MySQL driver to 8.0.29
  pom.xml
Labels: 2.0

#3645 DBZ-5301 FIx LogMinerHelperIT to work on Oracle RAC with multiple nodes
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/LogMinerHelperIT.java
Labels: 1.9, 2.0

#3646 DBZ-5303 Rework SkipOnDatabaseOption, allow for enabled/disabled toggles
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipOnDatabaseOption.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/junit/SkipTestDependingOnDatabaseOptionRule.java
Labels: 1.9, 2.0

#3648 DBZ-5251 Add debezium-quarkus-outbox to BOM
  debezium-bom/pom.xml
Labels: 1.9, 2.0

#3623 DBZ-5267 Invalid date 'SEPTEMBER 31'
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlStreamingChangeEventSource.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/RowDeserializers.java
Labels: 1.9, 2.0, pending tests

#3651 DBZ-5234 Add `oracle-ide` profile, simplifies IDE integrations
  debezium-connector-oracle/pom.xml
Labels: 1.9, 2.0

#3647 DBZ-5270 Reduce table schema capture logging verbosity
  debezium-core/src/main/java/io/debezium/relational/RelationalTableFilters.java
Labels: 1.9, 2.0

#3652 DBZ-5285 Fix store.only.captured.tables.ddl to work during streaming
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSchemaChangeEventEmitter.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
Labels: 1.9, 2.0

#3650 DBZ-5300 Exclude ADT indices as relational primary keys
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
Labels: 1.9, 2.0

#3670 DBZ-5332 Add Oracle 19.3 non-CDB to test matrix
  jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
Labels: 2.0
