Repository debezium/debezium, pull requests merged in 2022-07, with the labels that each got.

#3675 DBZ-4875 Deploy javadocs with nightly snapshots
  jenkins-jobs/pipelines/deploy-snapshots.groovy
Labels: 2.0

#3674 DBZ-5234 Rename `oracle-ide` to `oracle-all`
  debezium-connector-oracle/pom.xml
  jenkins-jobs/pipelines/deploy-snapshots.groovy
  jenkins-jobs/pipelines/release-pipeline.groovy
  jenkins-jobs/pipelines/system_pipeline.groovy
  jenkins-jobs/pipelines/upstream_artifact_server_prepare_pipeline.groovy
  jenkins-jobs/pipelines/upstream_kafka_connect_prepare_pipeline.groovy
  jenkins-jobs/scripts/release-pipeline.groovy
Labels: 1.9, 2.0

#3661 DBZ-5245 Track commit scn per redo thread
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/CommitScn.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerOracleOffsetContextLoader.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/events/LogMinerEventRow.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDatabaseHistoryTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleOffsetContextTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorUnitTest.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0

#3680 DBZ-5336 Add note about escaping dot (.) characters
  documentation/modules/ROOT/partials/modules/all-connectors/con-connector-incremental-snapshot.adoc
Labels: 1.9, 2.0

#3684 DBZ-5367 Fixed the problem where JSON expanding failed for Outbox eve…
  debezium-core/src/main/java/io/debezium/transforms/outbox/SchemaBuilderUtil.java
  debezium-core/src/test/java/io/debezium/transforms/outbox/EventRouterTest.java
Labels: 1.9, 2.0

#3689 DBZ-5346 Upgrade to Apache Kafka 3.2.0
  debezium-server/debezium-server-dist/src/main/resources/assemblies/server-distribution.xml
  pom.xml
Labels: 1.9

#3697 DBZ-5381 Add a pretty loggable format for commit_scn
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/CommitScn.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
Labels: 2.0

#3711 DBZ-5295 Exclude test for wal2json
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresConnectorIT.java
Labels: 1.9

#3712 DBZ-5403 Convert timestamps with tz default values to GMT
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/connection/PostgresDefaultValueConverter.java
Labels: 1.9, 2.0

#3710 DBZ-5390 Reorder relational_property definition to give priority to out_of_line_constraint
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 1.9, 2.0

#3717 DBZ-5399 Clarify database name usage in signal.data.collection for Oracle
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0

#3719 DBZ-5411 Fix Oracle non-cdb builds to use correct env variables
  jenkins-jobs/pipelines/connector_oracle_matrix_pipeline.groovy
Labels: 2.0

#3700 DBZ-5392 added downstream/upstream suffix to the preparation jenkins …
  jenkins-jobs/job-dsl/ocp_downstream_apicurio_prepare.groovy
  jenkins-jobs/job-dsl/ocp_downstream_artifact_server_prepare.groovy
  jenkins-jobs/job-dsl/ocp_downstream_strimzi_prepare.groovy
  jenkins-jobs/job-dsl/ocp_downstream_trigger_all_prepare.groovy
  jenkins-jobs/job-dsl/ocp_upstream_kafka_connect_prepare.groovy
  jenkins-jobs/job-dsl/rhel_downstream_prepare.groovy
  jenkins-jobs/pipelines/downstream_preparations_trigger_pipeline.groovy
Labels: qe-review

#3731 DBZ-5248 Avoid NumberFormatException in OracleConnectorIT tests
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 1.9, 2.0

#3732 DBZ-4004 Fix SQL Server test EventProcessingFailureHandlingIT
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/EventProcessingFailureHandlingIT.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/util/TestHelper.java
Labels: 1.9, 2.0

#3736 DBZ-5433 stop OffsetStore if it fails to fully start
  debezium-embedded/src/main/java/io/debezium/embedded/EmbeddedEngine.java
Labels: 1.9, 2.0

#3735 DBZ-5249 KafkaDatabaseHistory without check database history topic create result caused UnknowTopicOrPartitionException
  COPYRIGHT.txt
  debezium-storage/debezium-storage-kafka/src/main/java/io/debezium/storage/kafka/history/KafkaDatabaseHistory.java
  documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
Labels: 2.0

#3730 DBZ-5427 Upgrade to Quarkus 2.11.0.Final
  pom.xml
Labels: 2.0

#3686 DBZ-5371 Use initial snapshot position if "$natural:-1" is not supported
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbSnapshotChangeEventSource.java
Labels: 1.9, 2.0

#3739 DBZ-5292 Treat SQLServerException with "Broken pipe (Write failed)" exception message as a retriable exception
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerErrorHandler.java
Labels: 1.9, 2.0

#3740 DBZ-5445 Upgrade formatter-maven-plugin to 2.20.0
  pom.xml
Labels: 2.0

#3741 DBZ-5446 Upgrade impsort-maven-plugin to 1.7.0
  pom.xml
Labels: 2.0

#3744 DBZ-5333 Caused by: java.io.EOFException: Failed to read next byte from position 2005308603
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlErrorHandler.java
Labels: 1.9, 2.0

#3743 DBZ-5450 Typo in postgresql document.
  documentation/modules/ROOT/pages/connectors/postgresql.adoc
Labels: 1.9, 2.0

#3745 DBZ-5452 Fix unit test failing on Windows platform
  debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedSnapshotChangeEventSourceTest.java
Labels: 2.0

#3751 [docs] Avoiding reference to Guava types
  documentation/modules/ROOT/pages/integrations/testcontainers.adoc
Labels: 1.9, 2.0

#3752 [docs] Removing obsolete ZK reference from tutorial
  documentation/modules/ROOT/partials/modules/tutorial/proc-starting-kafka-connect.adoc
Labels: 1.9, 2.0

#3754 DBZ-5457 Deprecate legacy topic selector for all connectors
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/MongoDbTopicSelector.java
  debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/TopicSelectorTest.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlTopicSelector.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleTopicSelector.java
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/PostgresTopicSelector.java
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerTopicSelector.java
  debezium-core/src/main/java/io/debezium/schema/TopicSelector.java
Labels: 2.0

#3747 DBZ-5422 Update link format and multiple edits
  documentation/modules/ROOT/partials/modules/tutorial/con-introduction-debezium.adoc
Labels: 1.9, 2.0

#3757 DBZ-5441 Gracefully skip Oracle non-relational tables
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/CreateTableParserListener.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 1.9, 2.0
