Repository debezium/debezium, pull requests merged in 2023-01, with the labels that each got.

#4164 [docs] Typo fix in Oracle connector documentation
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 1.9, 2.0, 2.1

#4187 DBZ-5998 Use correct format for GITHUB_OUTPUT in CI
  .github/workflows/contributor-check.yml
  .github/workflows/octocat-commits-check.yml
  .github/workflows/oracle-workflow-test.yml
  .github/workflows/sanity-check.yml
Labels: 2.0, 2.1

#4158 DBZ-5930: Add the doc for vitess snapshot.mode
  documentation/modules/ROOT/pages/connectors/vitess.adoc
Labels: waits for docs review
