Repository debezium/debezium, pull requests merged in 2023-08, with the labels that each got.

#4720 DBZ-6733 Skip mining distance calc. if upper bounds not within distance
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 2.3, 2.4

#4738 DBZ-6751 Fix failing test OracleSchemaMigrationIT
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
Labels: 2.4

#4731 DBZ-6743 Remove duplicate query.fetch.size definition
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
Labels: 2.3

#4729 DBZ-6740 Upgrade to Quarkus 3.2.3.Final
  pom.xml
Labels: 2.3, 2.4

#4746 DBZ-6754 Prepares content for downstream use
  documentation/modules/ROOT/pages/configuration/notification.adoc
Labels: 2.3, 2.4

#4755 DBZ-6782 Properly solve XMLTYPE data types during DDL changes
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleXmlDataTypesIT.java
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 2.4

#4782 DBZ-6798 Expose SCN-based metrics as `BigInteger`
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetrics.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleStreamingChangeEventSourceMetricsMXBean.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/Scn.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.3, 2.4

#4783 DBZ-6801 Introduce JDBC sink option `dialect.sqlserver.identity.insert`
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: waits for other PR

#4789 DBZ-6813 Improve Infinispan configuration example
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.4

#4798 Fix minor typos in ExtractNewRecordState docs
  COPYRIGHT.txt
  debezium-core/src/main/java/io/debezium/transforms/ExtractNewRecordState.java
Labels: 2.3, 2.4

#4799 DBZ-6821 Dbz crashes on DDL statement (non Latin chars in variables)
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
Labels: 2.3, 2.4
