Repository debezium/debezium, pull requests merged in 2023-10, with the labels that each got.

#4900 DBZ-6738 create OLM manifest archive during operator release
  jenkins-jobs/job-dsl/release/release_upstream.groovy
  jenkins-jobs/pipelines/release/release-pipeline.groovy
Labels: 2.4

#4899 DBZ-6968 Added units to the documentation of cursor.oversize.skip.threshold
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 2.4

#4898 DBZ-6973 Documentation for filters.match.mode configuration
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 2.4

#4908 DBZ-6992 Update Quarkus dev version to compile with JDK 21
  pom.xml
Labels: 2.5

#4897 DBZ-6983 Add the ability to sanitize field name when inferencing json schema
  debezium-core/src/main/java/io/debezium/transforms/outbox/EventRouterDelegate.java
  debezium-core/src/main/java/io/debezium/transforms/outbox/JsonSchemaData.java
  debezium-core/src/test/java/io/debezium/transforms/outbox/JsonSchemaDataTest.java
Labels: 2.5

#4926 DBZ-6975 Correctly handle escaped single-quotes in UNISTR arguments
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/UnistrHelper.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 2.5

#4925 DBZ-7006 Properly handle escaped CLOB single-quotes
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
Labels: 2.3, 2.4, 2.5

#4901 DBZ-6970 Add the new property "truncate.enabled" to jdbc doc
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: waits for other PR, 2.5

#4951 DBZ-7055 Upgrade maven-surefire-plugin to 3.1.2
  pom.xml
Labels: 2.5

#4958 DBZ-7067 Improve Oracle logging for COMMITs
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 2.5
