Repository debezium/debezium, pull requests merged in 2023-06, with the labels that each got.

#4571 DBZ-6519 Parse mysql table name failed which ending with backslash
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
Labels: upstream first

#4607 DBZ-6359 Allow specifying SIDs in Oracle `rac.nodes` parameter
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/logwriter/RacCommitLogWriterFlushStrategy.java
Labels: 2.3

#4606 DBZ-6528 Fix Oracle NPE when storing only captured table schemas with signals
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Labels: 2.2, 2.3

#4647 DBZ-6619 Fix Connector postgres driver v42.5.0 has a vulnerability CVE-2022-41946 issue
  pom.xml
Labels: 2.4
