Repository debezium/debezium, pull requests merged in 2023-11, with the labels that each got.

#4992 DBZ-7120 Add a connection max retry limit to Redis schema history
  debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/RedisCommonConfig.java
  debezium-storage/debezium-storage-redis/src/main/java/io/debezium/storage/redis/history/RedisSchemaHistory.java
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
Labels: 2.5

#4996 DBZ-6942 Verify no log sequence gaps on log switch
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/LogMinerHelperTest.java
Labels: 2.5

#5004 DBZ-7135 Run MySQL CI configurations concurrently on GitHub
  .github/workflows/debezium-workflow.yml
  debezium-connector-mysql/pom.xml
Labels: 2.5

#5002 [docs] Docs for `ConvertCloudEventToSaveableForm`
  documentation/modules/ROOT/nav.adoc
  documentation/modules/ROOT/pages/transformations/convert-cloudevent-to-saveable-form.adoc
  documentation/modules/ROOT/pages/transformations/index.adoc
Labels: waits for other PR

#5020 DBZ-7158 Treat Oracle RAC redo thread log sequences independently
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/LogMinerHelperTest.java
Labels: 2.4, 2.5

#5045 DBZ-7144 Upgrade protobuf-java-util to 3.25.1
  pom.xml
Labels: 2.4, 2.5

#5042 DBZ-7187 Upgrade to Infinispan 14.0.20.Final
  pom.xml
Labels: 2.5

#5054 DBZ-6636 Document JDBC sink field include/exclude list
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: 2.5
