Repository debezium/debezium, pull requests merged in 2023-04, with the labels that each got.

#4420 DBZ-6274 Fix compatibility with Oracle tests and Infinispan 14
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 2.1, 2.2

#4421 DBZ-6275 Correctly sync Infinispan cache on event counter reset
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/AbstractInfinispanLogMinerEventProcessor.java
Labels: 2.1, 2.2

#4422 DBZ-6273 Fix Infinispan serialization of table names with spaces
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/infinispan/marshalling/LogMinerEventAdapter.java
Labels: 2.1, 2.2

#4418 DBZ-6271 allow binlog to be absent when doing a snapshot only
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSnapshotChangeEventSource.java
Labels: needs more thinking

#4445 DBZ-6318 Remove outdated SYS account usage
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.1, 2.2

#4441 DBZ-5395 Improve Oracle offset management when LOB enabled
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 2.2

#4498 [docs] Wrong download link for jdbc connector
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: 2.2
