Repository debezium/debezium, pull requests merged in 2024-10, with the labels that each got.

#5913 DBZ-8294 Use connect:nightly rather than connect-base:latest
  debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/TestInfrastructureHelper.java
Labels: 3.0

#5916 DBZ-7040 Fix Oracle DDL parsing to strip trailing new lines
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/OracleDdlParser.java
Labels: 2.7, 3.0

#5920 DBZ-8304 Fix column reselection for Oracle
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
Labels: 2.7, 3.0

#5917 DBZ-8292 Make ORA-01001 invalid cursor errors to be retried
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 3.0

#5933 DBZ-8318 Explain how to manage SPI and bundled jars for debezium engine applications
  documentation/modules/ROOT/pages/development/engine.adoc
Labels: waits for docs review

#5951 DBZ-8316 Support POSITION keyword as column name
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 2.7, 3.0

#5952 DBZ-8315 Add in-memory-clause support for sub-partition lists
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 2.7, 3.0

#5953 DBZ-8345 Don't fault archive log only mode when SCN is unavailable
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileNotFoundException.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 3.0

#5964 DBZ-8208 Use the Loggings utility class
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 3.0
