Repository debezium/debezium, pull requests merged in 2024-09, with the labels that each got.

#5811 DBZ-8184 Enable snapshot failure retries during Oracle tests
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 3.0

#5821 DBZ-8199 Fix test to resolve database name from environment
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorTest.java
Labels: 2.7, 3.0

#5820 DBZ-8198 Exclude Oracle vecsys tablespace from capture
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.7, 3.0

#5819 DBZ-8197 Increase wait time for XStream
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 3.0

#5827 DBZ-8201 Reduce log verbosity on OpenLogReplicator confirmation
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/olr/client/OlrNetworkClient.java
Labels: 2.7, 3.0

#5829 [ci] Bump impsort-maven-plugin from 1.11.0 to 1.12.0
  pom.xml
Labels: dependencies, 3.0

#5834 DBZ-5009 Make ORA-00600 error `krvrdccs10` retriable
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 3.0

#5832 DBZ-8208 Extend `error.processing.failure.handling.mode` to DML parsing
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 2.7, 3.0

#5846 DBZ-8226 Bump MariaDB to 11.4.3
  debezium-connector-mariadb/pom.xml
Labels: 2.7, 3.0

#5852 DBZ-8223 Make ORA-00600 krvrdccs30 retriable
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 2.7, 3.0

#5861 DBZ-7198 Fix shouldConvertToAvro key failure with serialization
  debezium-testing/debezium-testing-testcontainers/src/test/java/io/debezium/testing/testcontainers/ApicurioRegistryTest.java
Labels: 3.0

#5868 DBZ-8241 Use pre-defined builder factory when none is specified
  debezium-api/src/main/java/io/debezium/engine/DebeziumEngine.java
  debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
Labels: 2.7, 3.0

#5867 DBZ-8246 Bump Infinispan to 15.0.8.Final
  pom.xml
Labels: 3.0

#5862 DBZ-8245 Use `debezium/connect:nightly` for JDBC sink e2e tests
  debezium-connector-jdbc/src/test/docker/debezium-connect-with-oracle-driver/Dockerfile
  debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/junit/jupiter/e2e/source/SourcePipelineInvocationContextProvider.java
Labels: 3.0

#5875 DBZ-8248 Support `EMPTY_CLOB` and `EMPTY_BLOB` default values
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDefaultValueConverter.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDefaultValueIT.java
Labels: 2.7, 3.0

#5885 DBZ-8263 Common binlog code does not depend on MariaDB
  debezium-connector-binlog/pom.xml
Labels: 2.7, 3.0

#5886 DBZ-8267 Fix test failures
  debezium-embedded/src/test/java/io/debezium/embedded/AbstractConnectorTest.java
  debezium-embedded/src/test/java/io/debezium/pipeline/AbstractBlockingSnapshotTest.java
Labels: 2.7

#5884 DBZ-8261 Allow removal of Oracle deps from package
  debezium-assembly-descriptors/src/main/resources/assemblies/connector-distribution-no-infinispan.xml
  debezium-connector-jdbc/pom.xml
Labels: 2.7, 3.0

#5881 DBZ-8258 Override forced scope for dependency
  debezium-connector-mysql/pom.xml
Labels: 2.7, 3.0

#5883 DBZ-8260 Make Oracle NLS library provided
  LICENSE-3rd-PARTIES.txt
Labels: 2.7, 3.0

#5898 [docs] Remove brackets on snapshot select override examples
  documentation/modules/ROOT/pages/connectors/db2.adoc
  documentation/modules/ROOT/pages/connectors/informix.adoc
  documentation/modules/ROOT/pages/connectors/oracle.adoc
  documentation/modules/ROOT/pages/connectors/postgresql.adoc
  documentation/modules/ROOT/pages/connectors/sqlserver.adoc
Labels: 2.7, 3.0

#5897 DBZ-8212 Add support for integer arrays
  debezium-connector-postgres/src/main/java/io/debezium/connector/postgresql/UnchangedToastedPlaceholder.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/PostgresReselectColumnsProcessorIT.java
  debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
Labels: 2.7, 3.0
