Repository debezium/debezium, pull requests merged in 2024-08, with the labels that each got.

#5727 DBZ-8054 Workaround bug with ISPN and toList() collection
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractTransactionCachingLogMinerEventProcessor.java
Labels: 3.0

#5701 DBZ-8081 Conditionalize default value field of schema.history.internal.store.only.captured.databases.ddl property
  documentation/modules/ROOT/partials/modules/all-connectors/ref-connector-configuration-database-history-properties.adoc
Labels: 2.7, 3.0

#5711 DBZ-8095 Bump Quarkus to 3.8.5 & Apicurio to 2.5.8.Final
  pom.xml
Labels: 3.0

#5669 DBZ-8044 Add abandoned transaction details to log
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/processor/AbstractProcessorTest.java
  debezium-connector-oracle/src/test/resources/logback-test.xml
Labels: 2.7, 3.0

#5753 DBZ-8125 Make ORA-00600 errors related to `krvrdGetUID` retriable
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleErrorHandler.java
Labels: 2.7, 3.0

#5766 DBZ-8143 Add LogMiner start mining session retry attempt counter to logs
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 2.7, 3.0

#5772 DBZ-8148 Reduce XStream logging verbosity
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
Labels: 2.7, 3.0

#5768 DBZ-8145 Bump apicurio-registry to 2.6.2.Final
  pom.xml
Labels: 3.0

#5778 DBZ-8151 Allow `record_value` with no `primary.key.fields`
  debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfig.java
  debezium-connector-jdbc/src/test/java/io/debezium/connector/jdbc/JdbcSinkConnectorConfigTest.java
Labels: 2.7, 3.0

#5787 DBZ-8164 Upgrade Outbox Extension to Quarkus 3.14.0
  debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxCommonConfig.java
  debezium-quarkus-outbox-common/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxEventHbmWriter.java
  debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxCommonRuntimeConfig.java
  debezium-quarkus-outbox-reactive/deployment/src/main/java/io/debezium/outbox/reactive/quarkus/deployment/DebeziumOutboxConfig.java
  debezium-quarkus-outbox-reactive/deployment/src/main/java/io/debezium/outbox/reactive/quarkus/deployment/OutboxProcessor.java
  debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/AbstractEventDispatcher.java
  debezium-quarkus-outbox-reactive/runtime/src/main/java/io/debezium/outbox/reactive/quarkus/internal/DebeziumOutboxRuntimeConfig.java
  debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/DebeziumOutboxConfig.java
  debezium-quarkus-outbox/deployment/src/main/java/io/debezium/outbox/quarkus/deployment/OutboxProcessor.java
  debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/AbstractEventDispatcher.java
  debezium-quarkus-outbox/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxRuntimeConfig.java
  pom.xml
Labels: 3.0

#5786 DBZ-8162 Fix open redo log consistency with reopening nodes
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogFileCollector.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogFileCollectorTest.java
Labels: 2.7, 3.0

#5499 DBZ-7797 Fail fast if surrogate key for incremental snapshot doesn't exist
  debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractChunkQueryBuilder.java
  debezium-core/src/test/java/io/debezium/pipeline/source/snapshot/incremental/DefaultChunkQueryBuilderTest.java
Labels: pending tests

#5580 DBZ-7876 Improve NATS Jetstream sink properties for authentication
  COPYRIGHT.txt
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
  jenkins-jobs/scripts/config/Aliases.txt
Labels: waits for docs review

#5803 DBZ-8178 Fix Ehcache JAXB dependencies
  debezium-connector-oracle/pom.xml
Labels: 3.0

#5808 DBZ-8032 Use better exception than NullPointerException
  debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Labels: 2.7, 3.0

#5814 DBZ-8188 Use new connection on attach retries
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
Labels: 2.7, 3.0

#5809 DBZ-8181 Drop several deprecated Oracle configuration options
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorConfigTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 3.0
