Repository debezium/debezium, pull requests merged in 2024-01, with the labels that each got.

#5130 DBZ-7288 Unittest for hasCommitAlreadyBeenHandled in CommitScn Class
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/CommitScnTest.java
Labels: 2.6

#5127 DBZ-7286 Support Several Table Specification in the "CREATE TABLE" in ORACLE
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 2.6

#5160 DBZ-7352 Upgrade to Quarkus 3.6.5
  pom.xml
Labels: 2.6

#5168 DBZ-7313 Provide more precise description of metric
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 2.6

#5166 DBZ-7358 Use relational table primary key by default
  debezium-core/src/main/java/io/debezium/processors/reselect/ReselectColumnsPostProcessor.java
  documentation/modules/ROOT/pages/post-processors/reselect-columns.adoc
Labels: 2.5, 2.6

#5171 DBZ-7366 use `withMaskedPasswords()` to mask password of `JdbcSchemaHistory` config
  debezium-storage/debezium-storage-jdbc/src/main/java/io/debezium/storage/jdbc/JdbcCommonConfig.java
Labels: 2.5, 2.6

#5210 DBZ-7431 Document JDBC connector sink option `connection.provider`
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: waits for other PR, 2.5, 2.6
