Repository debezium/debezium, pull requests merged in 2024-07, with the labels that each got.

#5640 DBZ-7965 Use Maven 3.9.8 for Debezium builds
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  CONTRIBUTE.md
  README.md
  README_JA.md
  README_KO.md
  README_ZH.md
  mvnw
  mvnw.cmd
  pom.xml
Labels: 3.0

#5662 DBZ-8023 check PDB field against both null and blank
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
Labels: 3.0

#5676 DBZ-8058 Connection will be validated and re-connect if not valid
  debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java
  debezium-core/src/main/java/io/debezium/relational/RelationalSnapshotChangeEventSource.java
Labels: 2.7, 3.0

#5681 DBZ-8063 Add documentation for webhook auth config
  documentation/modules/ROOT/pages/operations/debezium-server.adoc
Labels: waits for other PR, 3.0

#5690 DBZ-8066 Support RENAME TABLE IF EXISTS
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
  debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_create.sql
Labels: 2.7, 3.0

#5691 DBZ-8070 Change some log entries to debug level
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 2.7, 3.0

#5655 DBZ-8010 Bump Infinispan to 14.0.29.Final
  pom.xml
Labels: 2.7, 3.0

#5694 DBZ-8018 Add note to JDBC documentation about the primary.key.fields
  documentation/modules/ROOT/pages/connectors/jdbc.adoc
Labels: 2.7, 3.0

#5696 DBZ-8076 Support capturing BLOB during snapshots
  debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/jdbc/BinlogValueConverters.java
  debezium-connector-binlog/src/test/java/io/debezium/connector/binlog/BinlogBinaryModeIT.java
Labels: 2.7, 3.0

#5708 DBZ-8089 Reset column scale on MODIFY ddl statements
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleSchemaMigrationIT.java
Labels: 2.7, 3.0

#5712 [docs] Add `driver.*` namespace pass-through section for PostgreSQL
  documentation/modules/ROOT/pages/connectors/postgresql.adoc
Labels: 2.7, 3.0

#5714 DBZ-8088 Add MariaDB connector to release pipeline
  jenkins-jobs/pipelines/release/release-pipeline.groovy
Labels: 3.0

#5715 DBZ-8099 Add MariaDB Connector/J License
  LICENSE-3rd-PARTIES.txt
Labels: 2.7, 3.0

#5713 DBZ-3656 Use `online_catalog` as default strategy
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 3.0

#5719 DBZ-8102 Make ORA-26928 "Unable to communicate with XStream apply coordinator process" retriable
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/XstreamStreamingChangeEventSource.java
Labels: 2.7, 3.0

#5717 DBZ-8055 Cap LogMiner range to min open redo thread last scn
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 2.7, 3.0

#5721 DBZ-8104 Fix converters documentation examples
  documentation/modules/ROOT/pages/connectors/oracle.adoc
  documentation/modules/ROOT/partials/modules/all-connectors/shared-mariadb-mysql.adoc
Labels: 2.7, 3.0
