Repository debezium/debezium, pull requests merged in 2024-05, with the labels that each got.

#5534 DBZ-7841 Bump Quarkus to 3.8.3 for Debezium Server
  pom.xml
Labels: 2.7

#5535 DBZ-7842 Bump Quarkus to 3.10.0 for Outbox Extension
  pom.xml
Labels: 2.7

#5536 DBZ-7785 Add MariaDB REST extension tests
  debezium-connector-mariadb/src/main/resources/META-INF/services/org.apache.kafka.connect.rest.ConnectRestExtension
  debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/rest/DebeziumMariaDbConnectorResourceIT.java
  debezium-connector-mariadb/src/test/java/io/debezium/connector/mariadb/rest/DebeziumMariaDbConnectorResourceNoDatabaseIT.java
  debezium-connector-mariadb/src/test/resources/Dockerfile.rest.test
  debezium-testing/debezium-testing-testcontainers/pom.xml
  debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/ConnectorResolver.java
  debezium-testing/debezium-testing-testcontainers/src/main/java/io/debezium/testing/testcontainers/testhelper/RestExtensionTestInfrastructure.java
Labels: waits for other PR, 2.7

#5524 DBZ-4332 Add `row_id` to Oracle event's source info block
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleOffsetContext.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSourceInfoStructMaker.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/SourceInfo.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/xstream/LcrEventHandler.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SourceInfoTest.java
Labels: 2.7

#5527 DBZ-4332 Update documentation about `row_id`
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: waits for other PR, 2.7

#5539 DBZ-7790 Improve LOB merge when table is keyless
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerHelper.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/TransactionCommitConsumer.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
Labels: 2.7

#5552 DBZ-7841 Rollback to Quarkus 3.2.12
  pom.xml
Labels: 2.7

#5553 DBZ-7863 Enforce Java 11 bytecode
  pom.xml
Labels: waits for other PR

#5591 DBZ-7882 Apply `decimal.handling.mode` to 0-scale numeric values
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
Labels: 2.7
