Repository debezium/debezium, pull requests merged in 2025-04, with the labels that each got.

#6285 DBZ-8864 Upgdare RocketMQ to 5.2.0
  pom.xml
Labels: 3.2

#6281 DBZ-8867 Bump Chicory and use ByteArrayMemory
  debezium-bom/pom.xml
  debezium-scripting/debezium-scripting/src/main/java/io/debezium/transforms/scripting/wasm/ChicoryEngine.java
Labels: 3.2

#6287 DBZ-8868 Make getHistoryRecordComparator() public
  debezium-connector-mariadb/src/main/java/io/debezium/connector/mariadb/MariaDbConnectorConfig.java
  debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-sqlserver/src/main/java/io/debezium/connector/sqlserver/SqlServerConnectorConfig.java
  debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalDatabaseConnectorConfig.java
Labels: 3.2

#6284 Log JMX MBean name when registration fails
  debezium-core/src/main/java/io/debezium/pipeline/JmxUtils.java
Labels: 3.2

#6280 DBZ-8788 Document mTLS using JKS with Oracle
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 3.0, 3.1

#6301 DBZ-8880 Clear events for abandoned transaction over threshold
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 3.0, 3.1, 3.2

#6306 DBZ-8889 Fix ISOSTRING conversion for Oracle timestamps
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/AbstractOracleDatatypesTest.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/SnapshotDatatypesIT.java
Labels: 3.1, 3.2

#6319 DBZ-8905 Upgrade Outbox Extension to Quarkus 3.21.2
  pom.xml
Labels: 3.2

#6320 DBZ-8906 Update to Quarkus LTS 3.15.4
  pom.xml
Labels: 3.2

#6317 DBZ-8895 Add Oracle virtual column `BY USER FOR STATISTICS` clause
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 3.1, 3.2

#6329 DBZ-8919 Ignore continuous mining config on Oracle 18+
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 3.1, 3.2

#6318 DBZ-8874 Guard against silent Ehcache evictions
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/CacheCapacityExceededException.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheEvictionListener.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerCache.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerEventProcessor.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/ehcache/EhcacheLogMinerTransactionCache.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/EhcacheIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/util/TestHelper.java
  debezium-core/src/test/java/io/debezium/junit/logging/LogInterceptor.java
Labels: 3.1, 3.2

#6338 Remove obsolete documented MongoDB connector configurations
  documentation/modules/ROOT/pages/connectors/mongodb.adoc
Labels: 3.0, 3.1, 3.2

#6337 DBZ-8921 Remove extra filter check for non-hybrid strategies
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 3.1, 3.2

#6344 DBZ-8927 Add MariaDB connector link to Installation Guide
  documentation/antora.yml
  documentation/modules/ROOT/pages/install.adoc
Labels: 2.7, 3.0, 3.1, 3.2

#6342 DBZ-8925 Improve Hybrid strategy performance with the Oracle ObjectId cache
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleDatabaseSchema.java
Labels: 3.1, 3.2

#6351 DBZ-8936 Shut down gracefully upon StopEngineException
  debezium-embedded/src/main/java/io/debezium/embedded/async/AsyncEmbeddedEngine.java
  debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertAsyncConsumerProcessor.java
  debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAndConvertConsumerProcessor.java
  debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtAsyncConsumerProcessor.java
  debezium-embedded/src/main/java/io/debezium/embedded/async/ParallelSmtConsumerProcessor.java
  debezium-embedded/src/test/java/io/debezium/embedded/async/AsyncEmbeddedEngineTest.java
Labels: 3.1, 3.2

#6343 DBZ-8926 Fetch `OBJ# %` rows only when using Hybrid with query filters
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilder.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerQueryBuilderTest.java
Labels: 3.1, 3.2

#6352 DBZ-8938 Remove unnecessary metadata query & map gets
  debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
Labels: 3.1, 3.2

#6357 DBZ-8944 Improve logging for partial rollback failures
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 3.2

#6355 DBZ-8943 Handle error codes 8180 through 8189 universally
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/AbstractStreamingAdapter.java
Labels: 3.1, 3.2

#6358 DBZ-8946 pass topic name in exception
  debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcKafkaSinkRecord.java
Labels: 3.2

#6363 DBZ-8971 Turn off open telemetry agent logging
  debezium-connector-mariadb/pom.xml
  debezium-connector-mongodb/pom.xml
  debezium-connector-mysql/pom.xml
  debezium-connector-postgres/pom.xml
Labels: 3.1, 3.2

#6372 DBZ-8995 Make StreamingChangeEventSource closeable
  debezium-core/src/main/java/io/debezium/pipeline/ChangeEventSourceCoordinator.java
  debezium-core/src/main/java/io/debezium/pipeline/source/spi/StreamingChangeEventSource.java
Labels: 3.2
