Repository debezium/debezium, pull requests merged in 2025-07, with the labels that each got.

#6545 DBZ-9191 Apply relaxed quoting heuristics to inserted values
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
Labels: 3.2

#6547 [docs] Mention Embeddings SMT Java requirements
  documentation/modules/ROOT/pages/ai/embeddings.adoc
Labels: 3.1, 3.2

#6502 DBZ-9110 Update OpenLineage required dependencies after moving then in dedicated module
  documentation/modules/ROOT/pages/integrations/openlineage.adoc
Labels: 3.3

#6559 DBZ-9219 Update to Quarkus 3.23.4 - Align with Hibernate 7.x
  debezium-quarkus-outbox-common/runtime/src/main/java/io/debezium/outbox/quarkus/internal/DebeziumOutboxMetadataSourcesContributor.java
  debezium-quarkus-outbox-reactive/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
  debezium-quarkus-outbox-reactive/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.MetadataSourcesContributor
  debezium-quarkus-outbox/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.AdditionalJaxbMappingProducer
  debezium-quarkus-outbox/runtime/src/main/resources/META-INF/services/org.hibernate.boot.spi.MetadataSourcesContributor
  pom.xml
Labels: 3.2, 3.3

#6576 DBZ-9236 Add display name for transaction snapshot boundary mode
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
Labels: 3.2, 3.3

#6570 DBZ-9232 Fix MongoDB additional conditions on first incremental chunk
  debezium-connector-mongodb/src/main/java/io/debezium/connector/mongodb/snapshot/MongoDbIncrementalSnapshotChangeEventSource.java
  debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/IncrementalSnapshotIT.java
Labels: 3.2, 3.3

#6578 DBZ-9238 Add `ONLINE` to Oracle `split_table_partition`
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 3.2, 3.3

#6590 DBZ-9272 Add option to use CTE-based LogMiner queries
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/AbstractLogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerQueryBuilder.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/unbuffered/UnbufferedLogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/CteQueryIT.java
Labels: 3.2, 3.3

#6577 DBZ-9237 Do not immediately fail JDBC sink if create table fails
  debezium-connector-jdbc/src/main/java/io/debezium/connector/jdbc/JdbcChangeEventSink.java
Labels: 3.2, 3.3

#6606 DBZ-9132 Fix parsing of UNISTR values with nested `||` sequence
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/UnistrHelper.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/UnistrHelperTest.java
Labels: 3.2, 3.3

#6615 DBZ-8991 Add `NumberOfEventsInBuffer` JMX metric
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetrics.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSourceMetricsMXBean.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/buffered/BufferedLogMinerStreamingChangeEventSource.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerStreamMetricsTest.java
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 3.2, 3.3
