Repository debezium/debezium, pull requests merged in 2025-08, with the labels that each got.

#6623 DBZ-9322 Log all V$LOGMNR_LOGS rows on failures
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerDatabaseStateWriter.java
Labels: 3.2, 3.3

#6631 DBZ-9332 Remove unncessary stubbing
  debezium-core/src/test/java/io/debezium/pipeline/EventDispatcherTest.java
Labels: 3.2, 3.3

#6638 DBZ-9343 Update assertj to 3.27.4
  debezium-bom/pom.xml
Labels: 3.3

#6630 DBZ-9331 Upgrade to Kafka 3.9.1
  pom.xml
Labels: 3.2

#6660 DBZ-9358 Support `IF EXISTS` for `RENAME COLUMN` clause
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
  debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_alter.sql
Labels: 3.2, 3.3

#6489 DBZ-9120 Add keepAlive to Schema Snapshot Table Lock Connection
  debezium-connector-binlog/src/main/java/io/debezium/connector/binlog/BinlogSnapshotChangeEventSource.java
Labels: under-discussion, 3.3

#6668 DBZ-9374 Fix OpenTelemetry testing agent path
  debezium-bom/pom.xml
  pom.xml
Labels: 3.2, 3.3

#6670 DBZ-9366 Adjust relaxed quote insert column value list parsing
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/parser/LogMinerDmlParser.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/LogMinerDmlParserTest.java
Labels: 3.2, 3.3

#6679 DBZ-9393 Relax check on `version` for OpenLineage emitted events
  debezium-connector-mongodb/src/test/java/io/debezium/connector/mongodb/OpenLineageIT.java
  debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OpenLineageIT.java
  debezium-connector-sqlserver/src/test/java/io/debezium/connector/sqlserver/OpenLineageIT.java
Labels: 3.2, 3.3

#6693 DBZ-9397 Support drop materialized view and log
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_drop.sql
Labels: 3.2, 3.3

#6692 DBZ-9406 Support Oracle RAC legacy variant of parallel_clause
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_create.sql
Labels: 3.2, 3.3
