Repository debezium/debezium, pull requests merged in 2025-02, with the labels that each got.

#6139 DBZ-8653 Emit LOB when available even when `lob.enabled` is off
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleBlobDataTypesIT.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleClobDataTypeIT.java
Labels: 3.0, 3.1

#6146 DBZ-8225 Add README for the JDBC sink connector
  debezium-connector-jdbc/README.md
Labels: 3.1

#6148 DBZ-8665 Improve performance for handling constraint violations
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 3.0, 3.1

#6156 [ci] Run tests on push to 3.0 branch
  .github/workflows/debezium-workflow-push.yml
Labels: 3.0

#6166 Update format-maven-plugin to 2.25.0
  pom.xml
Labels: 3.1

#6157 DBZ-8681 Avoid updating commit offsets for empty transactions with redo thread 0
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/processor/AbstractLogMinerEventProcessor.java
Labels: 3.0, 3.1

#6165 DBZ-8692 - Enhanced error messages on schema validation failures
  debezium-core/src/main/java/io/debezium/relational/TableSchemaBuilder.java
Labels: 3.1

#6180 DBZ-8725 Fix ill-formed SQL query when archive.log.hours > 0
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/SqlUtils.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/logminer/SqlUtilsTest.java
Labels: 3.0, 3.1

#6174 DBZ-8710 Allow specifying case-sensitive database and PDB names
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnectorConfig.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/util/OracleUtils.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleConnectorIT.java
Labels: 3.1

#6184 DBZ-8720 Support `ON NULL` in modify column clause
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/oracle/generated/PlSqlParser.g4
  debezium-ddl-parser/src/test/resources/oracle/examples/ddl_alter.sql
Labels: 3.0, 3.1

#6190 DBZ-8436 Add MariaDB `max_statement_time` user resource option
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBLexer.g4
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mariadb/generated/MariaDBParser.g4
  debezium-ddl-parser/src/test/resources/mariadb/examples/fast/ddl_alter.sql
Labels: 3.0, 3.1

#6185 DBZ-8700 Only reset scale when column type is modified
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/antlr/listener/ColumnDefinitionParserListener.java
  debezium-connector-oracle/src/test/java/io/debezium/connector/oracle/OracleDdlParserTest.java
Labels: 3.0, 3.1

#6189 DBZ-8559 Allow scalar expressions in Percona SEQUENCE_TABLE
  debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4
  debezium-ddl-parser/src/test/resources/mysql/examples/ddl_create.sql
Labels: 3.0, 3.1

#6191 DBZ-8159 Add section about Oracle mTLS connectivity
  documentation/modules/ROOT/pages/connectors/oracle.adoc
Labels: 3.0, 3.1

#6203 DBZ-8749 Account for database system tz in snapshot source ts_ms
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleConnection.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleSnapshotChangeEventSource.java
  debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/logminer/LogMinerStreamingChangeEventSource.java
Labels: 3.0, 3.1
